# true or false
verbose_mode: true

# Number of concurrent threads
threads_count: 50

# For the script to work properly, you must specify at least 1 public RPC
# Format: http://<ip>:<port> on each line
rpc_file_name: rpc_urls.txt

# The time during which the script will try to establish a connection
provider_timeout: 4

# Link to the file where the ip addresses of the nodes are located (optional)
genesis_file_url: http://localhost:26657/genesis
